#定义docker compose yml版本
version: "3"  
#定义我们的服务对象
services:
#自定义的服务名称
  nginx:
     #自定义容器的名称
     container_name: ${ENV_PROJECT_NAME}_nginx
     build: nginx
     #将宿主机的80端口映射到容器的80端口
     ports:
      - "9080:80"
     volumes:
      - ./www/:/usr/share/nginx/html/:rw
      - ./nginx/logs/:/var/logs/nginx/
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/startup.sh:/etc/nginx/startup.sh
     environment:
      - VIRTUAL_HOST=${VHOST}
      - TZ=${TZ}
     #容器加入名为lnmp的网络
     networks:
      - lnmp
     env_file:
      - .env
  phpfpm:
    container_name: ${ENV_PROJECT_NAME}_phpfpm
    build: phpfpm
    volumes:
      - ./www/:/usr/share/nginx/html/:rw
      - ./phpfpm/conf/:/usr/local/etc/php/conf.d/
      - ./phpfpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./phpfpm/log:/var/log/php
    environment:
      - TZ=${TZ}
    networks:
      - lnmp
    env_file:
      - .env

  mysql:
    container_name: ${ENV_PROJECT_NAME}_mysql
    build: mysql
    ports:
      - "9081:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql/:rw
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/log:/var/log/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${CONFIG_DB_PASSWORD}
      - TZ=${TZ}
    networks:
      - lnmp
    env_file:
      - .env

  redis:
    container_name: ${ENV_PROJECT_NAME}_redis
    build: redis
    ports:
      - ${CONFIG_REDIS_PORT}:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf:/usr/local/etc/redis
      - ./redis/logs:/logs
    command:
      redis-server /usr/local/etc/redis/redis.conf --appendonly yes --requirepass ${CONFIG_REDIS_PASSWORD}
    environment:
      - TZ=${TZ}
    networks:
      - lnmp
    env_file:
      - .env
networks:   
  #创建了一个自定义的网络叫做lnmp
  lnmp: